name: TestComplete Test

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Run TestComplete
        run: |
          echo "Running TestComplete"
          ssh ad\nilim.nath@192.168.1.126
          .\runner.bat
