name: TestComplete test

on:
  push:
    branches: 
      - main

jobs:
  test:
    #runs-on: 192.168.1.126
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Run TestComplete
        run: |
          echo "Running TestComplete"
          ssh ad\Administrator@172.31.30.178 .\runner.bat
