name: TestComplete Test

on:
 push:
  branches: 
   - main

jobs:
 test:
  runs-on: self-hosted
  
  steps:
   - name: Checkout code
     uses: actions/checkout@v3
   
   - name: Install TestExecute
     run: |
      choco install TestExecute -y 
