name: TestComplete Test

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: self-hosted
    instance-type: t2.xlarge

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run TestComplete
        run: |
          echo "Running TestComplete"
          "C:/Program Files (x86)/SmartBear/TestComplete 15/Bin/TestComplete.exe" "C:\Users\Administrator\Documents\TestComplete 15 Projects\TestProject2\TestProject2.pjs" /r /p:"TestProject2" /t:"KeywordTests:Test1" /exit /SilentMode
