name: TestComplete Test

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Run TestComplete - Step 1
        run: echo "Running TestComplete"

      - name: Run TestComplete - Step 2
        run: cd "C:\PerfLogs\x64\Bin\"

      - name: Run TestComplete - Step 3
        run: cmd.exe

      - name: Run TestComplete - Step 4
        run: TestComplete.exe "C:\Users\Administrator\Documents\TestComplete 15 Projects\TestProject2\TestProject2.pjs" /r /p:"TestProject2" /t:"KeywordTests|Test1" /exportLog:"C:\Users\Administrator\Desktop\Logs\results.html" /exit
  
