name: TestComplete Test

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Run TestComplete
        run: |
          echo "Running TestComplete"
          cd "C:\Users\Administrator\Documents" 
          .\runner.bat
