name: TestComplete Test

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run TestComplete
        run: |
          echo "Running TestComplete"
          
          cd "C:\PerfLogs\x64\Bin\"
          .\TestComplete.exe "$env:GITHUB_WORKSPACE/.github/workflows/TestProject2/TestProject2.pjs" /r /p:"TestProject2" /t:"KeywordTests|Test1"
