name: TestComplete Test

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: EC2AMAZ-25V74AM
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run TestComplete
        run: |
          echo "Running TestComplete"
          cd "C:\PerfLogs\x64\Bin"
          .\TestComplete.exe "C:/Users/Administrator/Documents/TestComplete 15 Projects/TestProject2/TestProject2.pjs" /r /p:"TestProject2" /t:"KeywordTests|Test1" /sl:"C:\Users\Administrator\Desktop\new-log.txt" /exit /SilentMode
