name: TestComplete Test

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run TestComplete
        run: |
          echo "Running TestComplete"
          "C:\PerfLogs\x64\Bin\TestComplete.exe" "C:\Users\Administrator\Documents\TestComplete 15 Projects\TestProject2\TestProject2.pjs" /run /p:"TestProject2" /t:"KeywordTests:Test1" /exit /SilentMode
